### ISSUE TITLE
the parms in jcl2sh 

### ISSUE THREAD

**Issue by arsela2018** [MikeFultonDev/JCL2SH#2]
Mike, good day,  a question, the sample in the README.MD: 
 jcl2sh <//'IBMUSER.TEST.JCL\(UPDATE\) >./update.sh
It don't send any message and neither create the update.sh ...
could you comment some action to verify the shell?

**Comment by ghost** [comment]
Correct. This scanner isn't 'done' yet and the shell script generation isn't there yet. It's not complete. I created an issue so that's more obvious to people. I'll add a note in the readme as well.
You can see how the processing is working if you use the '-d' and '-v' options. 
For example, if you go to the 'root' JCL2SH directory and then enter:
jcl2sh -d  -i=testsrc/cntl.jcl     

You will get an output similar to: 

```
Stmt 000000001     EXEC Lines:01 Ptr:2002AD80
Stmt 000000002     CNTL Lines:01 Ptr:2002AEB8
Stmt 000000003 PRINTDEV Lines:01 Ptr:2002AF50
Stmt 000000004  ENDCNTL Lines:01 Ptr:2002AFF8
Stmt 000000005       DD Lines:01 Ptr:2002B0A0
```
which is a dump of the statement tree for the corresponding JCL.

**Comment by MikeFultonDev** [comment]
I cleaned up the docs a bit and added a jcl2jcl parser.
